### PR TITLE
Fix screenshot error

### LINKED ISSUE #1906: Screenshot error message confusing (from 1.3.2680.SDK)
Trying to use USE_SWAPCHAIN_COLORSPACE I get the following message:

> screenshot: Selected format:USE_SWAPCHAIN_COLORSPACE
> Is NOT in the list:
> UNORM, SNORM, USCALED, SSCALED, UINT, SINT, SRGB
> Swapchain Colorspace will be used instead

This is confusing, is swapchain colorspace not in the list but it will be used? What is the error? The message could also explain what the list is. 

I don't remember seeing this message ever before

### PR DESCRIPTION
**Pull request by juan-lunarg**
The check should have been
```
value != "USE_SWAPCHAIN_COLORSPACE"
```

This is how it was originally written:
```
} else if (strcmp(vk_screenshot_format, "USE_SWAPCHAIN_COLORSPACE") != 0) {
```

I also made colorSpaceFormat an enum class.

closes #1906

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]

File: layersvt/screenshot.cpp [hunk 1]
```diff
@@ -278,20 +269,20 @@ static void init_screenshot(const VkInstanceCreateInfo *pCreateInfo, const VkAll
...
-            userColorSpaceFormat = SSCALED;
+            userColorSpaceFormat = colorSpaceFormat::SSCALED;
         } else if (value == "UINT") {
-            userColorSpaceFormat = UINT;
+            userColorSpaceFormat = colorSpaceFormat::UINT;
         } else if (value == "SINT") {
-            userColorSpaceFormat = SINT;
-        } else if (value == "USE_SWAPCHAIN_COLORSPACE") {
+            userColorSpaceFormat = colorSpaceFormat::SINT;
+        } else if (value != "USE_SWAPCHAIN_COLORSPACE") {
```
Comment (juan-lunarg) [inline layersvt/screenshot.cpp:285]: To be clear this is the fix. I just also updated the code to use an enum class for my benefit.

**Comment by juan-lunarg** [comment]
```
Launching Vulkan Application:
- Layers overridden by "Screenshot" configuration.
- Application: my_vkcube
- Executable: /Users/juanramos/projects/KHR-Vulkan-Tools/build/cube/vkcube.app/Contents/MacOS/vkcube
- Working Directory: /Users/juanramos/projects/KHR-Vulkan-Tools/build/cube/vkcube.app/Contents/MacOS
- Command-line Arguments: --suppress_popups
- Log file: /Users/juanramos/VulkanSDK/vkcube.txt

Selected GPU 0: Apple M2 Max, type: IntegratedGpu

screenshot: Capture file is: /Users/juanramos/VulkanSDK/1.ppm 

Process terminated
```

**Review by ziga-lunarg — APPROVED** [review]

**Comment by juan-lunarg** [comment]
Fixed from my Mac 💯
