### PR TITLE
devsim: Add image format properties

### LINKED ISSUE #1604: devsim: it doesn't support vkGetPhysicalDeviceImageFormatProperties()
When running this CTS tests with devsim and spec_minimum_vulkan_1_0.json by using the following command:

```
VK_DEVSIM_MODIFY_FORMAT_LIST=replace VK_DEVSIM_MODIFY_FORMAT_PROPERTIES=replace VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation:VK_LAYER_LUNARG_device_simulation VK_DEVSIM_FILENAME="${VULKAN_TOOLS}/layersvt/device_simulation_examples/sdk_sample_configs/spec_minimum_vulkan_1_0.json" ./deqp-vk -n dEQP-VK.glsl.builtin_var.simple.fragcoord_xyz
```

I found that the devsim layer was not replacing the image format properties in the [vkGetPhysicalDeviceImageFormatProperties()](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#vkGetPhysicalDeviceImageFormatProperties) at the check in [vktShaderRender.cpp](https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/vulkancts/modules/vulkan/shaderrender/vktShaderRender.cpp#L1838), so that it was returning the driver's image format properties. Therefore, the test creates the image, its view, and continue execution, resulting in validation errors.

```
Writing test log into TestResults.qpa
dEQP Core git-5d72b170aad664e4fcf770863d37bd041d45ff9b (0x5d72b170) starting..
  target implementation = 'Default'
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0


Test case 'dEQP-VK.glsl.builtin_var.simple.fragcoord_xyz'..
VUID-VkImageViewCreateInfo-None-02273(ERROR / SPEC): msgNum: 1066700753 - Validation Error: [ VUID-VkImageViewCreateInfo-None-02273 ] Object 0: handle = 0xfa21a40000000003, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x3f948fd1 | vkCreateImageView(): pCreateInfo->format VK_FORMAT_R1
6G16B16A16_UNORM with tiling VK_IMAGE_TILING_OPTIMAL has no supported format features on this physical device. The Vulkan spec states: The format features of the resultant image view must contain at least one bit (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vk
spec.html#VUID-VkImageViewCreateInfo-None-02273)
    Objects: 1
        [0] 0xfa21a40000000003, type: 10, name: NULL
MESA: debug: ../src/intel/vulkan/anv_device.c:100: VS SIMD8 shader: 6 inst, 0 loops, 20 cycles, 0:0 spills:fills, 1 sends, scheduled with mode top-down, Promoted 0 constants, compacted 96 to 64 bytes.
MESA: debug: ../src/intel/vulkan/anv_device.c:100: FS SIMD8 shader: 10 inst, 0 loops, 44 cycles, 0:0 spills:fills, 1 sends, scheduled with mode top-down, Promoted 0 constants, compacted 160 to 144 bytes.
MESA: debug: ../src/intel/vulkan/anv_device.c:100: FS SIMD16 shader: 10 inst, 0 loops, 54 cycles, 0:0 spills:fills, 1 sends, scheduled with mode top-down, Promoted 0 constants, compacted 160 to 144 bytes.
MESA: debug: ../src/intel/vulkan/anv_device.c:100: FS SIMD16 shader: 2 inst, 0 loops, 12 cycles, 0:0 spills:fills, 1 sends, scheduled with mode (null), Promoted 0 constants, compacted 32 to 32 bytes.
VUID-vkCmdCopyImageToBuffer-srcImage-01998(ERROR / SPEC): msgNum: -1387584025 - Validation Error: [ VUID-vkCmdCopyImageToBuffer-srcImage-01998 ] Object 0: handle = 0xfa21a40000000003, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xad4b25e7 | In vkCmdCopyImageToBuffer(), VkFormatFeatu
reFlags (0x00000000) does not support required feature VK_FORMAT_FEATURE_TRANSFER_SRC_BIT for format 91 used by VkImage 0xfa21a40000000003[] with tiling VK_IMAGE_TILING_OPTIMAL. The Vulkan spec states: The format features of srcImage must contain VK_FORMAT_FEATURE_TRANSFER_SRC_BIT 
(https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdCopyImageToBuffer-srcImage-01998)
    Objects: 1
        [0] 0xfa21a40000000003, type: 10, name: NULL
MESA: debug: ../src/intel/vulkan/anv_device.c:100: FS SIMD8 shader: 12 inst, 0 loops, 812 cycles, 0:0 spills:fills, 2 sends, scheduled with mode top-down, Promoted 0 constants, compacted 192 to 160 bytes.
MESA: debug: ../src/intel/vulkan/anv_device.c:100: FS SIMD16 shader: 12 inst, 0 loops, 830 cycles, 0:0 spills:fills, 2 sends, scheduled with mode top-down, Promoted 0 constants, compacted 192 to 160 bytes.
  Pass (Result image matches reference)

DONE!

Test run totals:
  Passed:        1/1 (100.0%)
  Failed:        0/1 (0.0%)
  Not supported: 0/1 (0.0%)
  Warnings:      0/1 (0.0%)
  Waived:        0/1 (0.0%)
```

Being the expected result:

```
Writing test log into TestResults.qpa
dEQP Core git-5d72b170aad664e4fcf770863d37bd041d45ff9b (0x5d72b170) starting..
  target implementation = 'Default'
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0


Test case 'dEQP-VK.glsl.builtin_var.simple.fragcoord_xyz'..
  NotSupported (Format not supported at vktShaderRender.cpp:1846)

DONE!

Test run totals:
  Passed:        0/1 (0.0%)
  Failed:        0/1 (0.0%)
  Not supported: 1/1 (100.0%)
  Warnings:      0/1 (0.0%)
  Waived:        0/1 (0.0%)
```

### PR DESCRIPTION
**Pull request by jeremyk-lunarg**
Added vkGetPhysicalDeviceImageFormatProperties function overrides to the
device simulation layer to properly curate format support for each
images based on simulated format properties list.

Fixes #1604

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
This is most probably very useful also I don't understand all of it... The bug mentions the devsim a configuration file so I am wondering whther the root cause is not that the devsim files are not correct regarding formats...

**Review by christophe-lunarg — APPROVED** [review]

File: layersvt/device_simulation.cpp [hunk 1]
```diff
@@ -4246,6 +4246,59 @@ VKAPI_ATTR void VKAPI_CALL GetPhysicalDeviceFormatProperties2KHR(VkPhysicalDevic
     GetPhysicalDeviceFormatProperties2(physicalDevice, format, pFormatProperties);
 }
 
+VKAPI_ATTR VkResult VKAPI_CALL GetPhysicalDeviceImageFormatProperties(VkPhysicalDevice physicalDevice, VkFormat format,
+                                                                      VkImageType type, VkImageTiling tiling,
+                                                                      VkImageUsageFlags usage, VkImageCreateFlags flags,
+                                                                      VkImageFormatProperties *pImageFormatProperties) {
+    std::lock_guard<std::mutex> lock(global_lock);
```
Comment (samuelig) [inline layersvt/device_simulation.cpp:4253]: When running the test in issue #1604, it got stuck [when trying to get the lock in `GetPhysicalDeviceFormatProperties()`](https://github.com/LunarG/VulkanTools/pull/1607/files#diff-a900e335f1854d7e8388801e46a065687ff1686fc8f97f77437656eb309b98c8R4155), because the lock was already grabbed in this line.

Comment (jeremyk-lunarg) [reply layersvt/device_simulation.cpp:4253]: Should be fixed now.

**Comment by jeremyk-lunarg** [comment]
Oh there we go.  I added the change but didn't commit it. -_-
